### ISSUE TITLE
Carthage update failed

### ISSUE THREAD

**Issue by izotx** [keygx/GradientCircularProgress#1]
I am getting a following error when I execute Carthage update command in terminal.
I am not sure how to proceed. I just updated to the newest version of Xcode which looks like might caused the problem.

*** Building scheme "GradientCircularProgress" in GCProgressSample.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/Property.swift
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/GradientArcView.swift
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/ProgressAtRatioView.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:76:22: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:85:30: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/Property.swift:15:38: error: use of unresolved identifier 'kCGLineCapButt'
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:76:22: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:85:30: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:76:22: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:85:30: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/GradientArcView.swift:45:13: warning: initialization of immutable value 'a0' was never used; consider replacing with assignment to '_' or removing it
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:76:22: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
/Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift:85:30: error: '#' has been removed from Swift; double up 'message message' to make the argument label the same as the parameter name
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/Property.swift
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/GradientCircularProgress.swift
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/GradientArcView.swift
	CompileSwift normal x86_64 /Users/janusz/Desktop/Repositories/twoKApp/Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progress/ProgressAtRatioView.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)

**Comment by keygx** [comment]
I merged the version that supported Swift 2.0 into a master branch.
Will you try it here?
