### ISSUE TITLE
Error with CocoaPods 1.0.0-beta6

### ISSUE THREAD

**Issue by Urkman** [keygx/GradientCircularProgress#11]
I updated to CocoaPods Version 1.0.0.

When I try to install my pods I get this error:

Pre-downloading: `GradientCircularProgress` from `https://github.com/keygx/GradientCircularProgress`
[!] The `GradientCircularProgress` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `summary`.

**Comment by keygx** [comment]
I updated podspec file and fixed this error.
