### ISSUE TITLE
installing using CocoaPods

### ISSUE THREAD

**Issue by iMarwan-k** [keygx/GradientCircularProgress#14]
Hello, when I tried install through CocoaPods I get this message "Unable to find a specification for `GradientCircularProgress`"

any help

**Comment by keygx** [comment]
Please try 
`$ sudo rm -rf ~/.cocoapods/repos/master`
`$ pod setup`

**Comment by iMarwan-k** [comment]
still same problem

**Comment by keygx** [comment]
The error is a thing of CocoaPods.
Are you the installation of the other libraries in CocoaPods?

**Comment by iMarwan-k** [comment]
Yes I'm able to install any other pods. I tried to install it in different project but still the same problem.

**Comment by keygx** [comment]
Is PodFile written rightly?
```
pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress'
```

**Comment by iMarwan-k** [comment]
this is the error im getting

[!] Error installing GradientCircularProgress
[!] /usr/bin/git clone https://github.com/keygx
GradientCircularProgress /var/folders/r4/1gpqklzd6ls973ytrs0qy9880000gn/T/d20160705-47171-1oclnv2 --template= --single-branch --depth 1

Cloning into '/var/folders/r4/1gpqklzd6ls973ytrs0qy9880000gn/T/d20160705-47171-1oclnv2'...
fatal: unable to access 'https://github.com/keygx
GradientCircularProgress/': Illegal characters found in URL
