### ISSUE TITLE
Carthage error Xcode 7.3.1

### ISSUE THREAD

**Issue by 1trycode** [keygx/GradientCircularProgress#16]
Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GradientCircularProgress/Progres*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
s/ProgressViewController.swift:40:47: error: getter for 'prefersStatusBarHidden' with Objective-C selector 'prefersStatusBarHidden' conflicts with method 'prefersStatusBarHidden()' from superclass 'UIViewController' with the same Objective-C selector
A shell task (/usr/bin/xcrun xcodebuild -project /Carthage/Checkouts/GradientCircularProgress/GCProgressSample/GCProgressSample.xcodeproj -scheme GradientCircularProgress -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by 1trycode** [comment]
this is the Cartfile cmd
github "keygx/GradientCircularProgress"

**Comment by 1trycode** [comment]
Oops I am not updated to Swift3.0

**Comment by keygx** [comment]
Please try it.

github "keygx/GradientCircularProgress" "3.3.1"
