### ISSUE TITLE
How to disable user interaction during progress.show()

### ISSUE THREAD

**Issue by guillaumebesse** [keygx/GradientCircularProgress#22]
It will be great to have a sort of BackgroundStyles.transparent 

Is it possible ?

**Comment by keygx** [comment]
No it is.

However, I will add a transparent background style at the next update.

**Comment by keygx** [comment]
Hi

Added "transparent" to the BackgroundStyle setting. -> Ver.3.6.0

```
public var backgroundStyle: BackgroundStyles = .transparent
```

In this setting, the background is transparent and user interaction is disabled.
