### ISSUE TITLE
Rounder border at the end of the arc

### ISSUE THREAD

**Issue by AndreaMiotto** [keygx/GradientCircularProgress#28]
Hey, is it possible to set the arc to finish with round border?

It should be possible just adding:  myPath.lineJoinStyle = kCGLineJoinRound
to the arc path...

**Comment by keygx** [comment]
Hi.
Thank you for your feedback.

> is it possible to set the arc to finish with round border?

No, it isn't possible.

**Comment by AndreaMiotto** [comment]
would you mind to add this feature? :)

**Comment by keygx** [comment]
Yes, it is difficult.
because the gradient will fail.
