### ISSUE TITLE
unknown pod name

### ISSUE THREAD

**Issue by choiks14** [keygx/GradientCircularProgress#33]
https://cocoapods.org/?q=GradientCircularProgress

cocoapods is not founded.

please help me.

**Comment by keygx** [comment]
GradientCircularProgress is not registered in the CocoaPods repository.
The installation specifies the repository of Github directly.

`pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress'`

**Comment by choiks14** [comment]
Aha.
Ok Thanks.
^^
