### ISSUE TITLE
Update for Swift 4.1

### ISSUE THREAD

**Issue by seenoevo** [keygx/GradientCircularProgress#34]
Can you please update this for Swift 4.1?

![untitled](https://user-images.githubusercontent.com/8109158/38480151-9fb3703a-3b78-11e8-9312-dfb64bd0b00d.png)

**Comment by keygx** [comment]
Please rebuild the library, after upgrading Swift.

**Comment by seenoevo** [comment]
@keygx 

I've tried cleaning and rebuilding multiple times with the same issue.

BTW: I'm not using CocoaPods, but rather dragging the source files and framework into my project.

There was no issue with this before the migration from Swift 4.0 -> 4.1

**Comment by keygx** [comment]
@seenoevo 
Please set _config.build_settings ['SWIFT_VERSION']_ to 4.1

--Podfile
`config.build_settings['SWIFT_VERSION'] = '4.1'`

**Comment by keygx** [comment]
@seenoevo 
I'm sorry. I was mistaken.

If you have successfully installed GradientCircularProgress.framework in your project, the error disappears when you rebuild the project.
