### ISSUE TITLE
Swift 4.2 and Xcode 10

### ISSUE THREAD

**Issue by shoaibnomani** [keygx/GradientCircularProgress#37]
Can you please update this library for swift 4.2 and Xcode 10?

**Comment by keygx** [comment]
I merged into the master branch.
Updated to support Swift 4.2 and Xcode 10.

**Comment by shoaibnomani** [comment]
> I merged into the master branch.
> Updated to support Swift 4.2 and Xcode 10.

Thank you so much.

**Comment by shoaibnomani** [comment]
> I merged into the master branch.
> Updated to support Swift 4.2 and Xcode 10.

In Xcode 10.1 and with swift 4.2 I'm having a strange issue. If I've set the background property to none using the StyleProperty class, I cannot tap on any other views on the view when the progress is displaying. The UI freezes. Previously with Xcode 9.4.1 and swift 4.1 there was no such issue.

**Comment by shoaibnomani** [comment]
> I merged into the master branch.
> Updated to support Swift 4.2 and Xcode 10.

In Xcode 10.1 and with swift 4.2 I'm having a strange issue. If I've set the background property to none using the StyleProperty class, I cannot tap on any other views on the view when the progress is displaying. The UI freezes. Previously with Xcode 9.4.1 and swift 4.1 there was no such issue.

**Comment by keygx** [comment]
Fix background property problem.

Please update to 3.11.0

**Comment by shoaibnomani** [comment]
> Fix background property problem.
> 
> Please update to 3.11.0

Great. It's working flawlessly now. Thanks a lot!
