### ISSUE TITLE
 Compiler error after update 

### ISSUE THREAD

**Issue by toka756** [keygx/GradientCircularProgress#5]
After I upgrade GradientCircularProgress  var cocoa pod, the compiler error appear.
I clean and restart Xcode(Version 7.1.1), but not fix the problem.

XXXX/Pods/GradientCircularProgress/Source/IndicatorStyle.swift:10:15: Type 'IndicatorStyle' does not conform to protocol 'StyleProperty'

XXXX//Pods/GradientCircularProgress/Source/OrangeDarkStyle.swift:10:15: Type 'OrangeDarkStyle' does not conform to protocol 'StyleProperty'

**Comment by toka756** [comment]
The compiler error disappeared after I remove  IndicatorStyle.swift and OrangeDarkStyle.swift file from library.

**Comment by keygx** [comment]
Thank you.
I forgot to delete the old file.
I removed the old files.
Error is gone.
