### ISSUE TITLE
embed inside a view

### ISSUE THREAD

**Issue by vyatri** [keygx/GradientCircularProgress#7]
how can i embed the circle inside a view?
Sorry for my poor English

**Comment by keygx** [comment]
Hi vyatri

This library draws arc.
It is not possible to fill the circle.

**Comment by keygx** [comment]
Hi vyatri

This library draws arc.
It is not possible to fill the circle.

**Comment by odedharth** [comment]
@keygx I think he meant if its possible to embed it inside a uiview instead of overlaying the entire screen.
I would also be interested in this open :smile:

**Comment by keygx** [comment]
Hi odedharth

Do you want to "addSubView(progress)" ?
I cannot provide it now.
However, I think about it.

**Comment by odedharth** [comment]
yes I think it could be very useful.

**Comment by keygx** [comment]
Added support for Embed in UIView at Ver.3.2.0.

```swift
let progress = GradientCircularProgress()

let progressView = progress.show(frame: rect, message: "Loading...", style: MyStyle())
view.addSubview(progressView!)

progress.dismiss(progress: progressView!)
```

Please try it.
